/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareersOccupationKeyRouteImport } from './routes/careers.$occupationKey'
import { Route as CareersOccupationKeyRealityCheckRouteImport } from './routes/careers.$occupationKey_.reality-check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOccupationKeyRoute = CareersOccupationKeyRouteImport.update({
  id: '/careers/$occupationKey',
  path: '/careers/$occupationKey',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOccupationKeyRealityCheckRoute =
  CareersOccupationKeyRealityCheckRouteImport.update({
    id: '/careers/$occupationKey_/reality-check',
    path: '/careers/$occupationKey/reality-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers/$occupationKey': typeof CareersOccupationKeyRoute
  '/careers/$occupationKey/reality-check': typeof CareersOccupationKeyRealityCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers/$occupationKey': typeof CareersOccupationKeyRoute
  '/careers/$occupationKey/reality-check': typeof CareersOccupationKeyRealityCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers/$occupationKey': typeof CareersOccupationKeyRoute
  '/careers/$occupationKey_/reality-check': typeof CareersOccupationKeyRealityCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/careers/$occupationKey' | '/careers/$occupationKey/reality-check'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/careers/$occupationKey' | '/careers/$occupationKey/reality-check'
  id:
    | '__root__'
    | '/'
    | '/careers/$occupationKey'
    | '/careers/$occupationKey_/reality-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersOccupationKeyRoute: typeof CareersOccupationKeyRoute
  CareersOccupationKeyRealityCheckRoute: typeof CareersOccupationKeyRealityCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$occupationKey': {
      id: '/careers/$occupationKey'
      path: '/careers/$occupationKey'
      fullPath: '/careers/$occupationKey'
      preLoaderRoute: typeof CareersOccupationKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$occupationKey_/reality-check': {
      id: '/careers/$occupationKey_/reality-check'
      path: '/careers/$occupationKey/reality-check'
      fullPath: '/careers/$occupationKey/reality-check'
      preLoaderRoute: typeof CareersOccupationKeyRealityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersOccupationKeyRoute: CareersOccupationKeyRoute,
  CareersOccupationKeyRealityCheckRoute: CareersOccupationKeyRealityCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
